version: "3.2"
services:
  mongo:
    image: mongo
    restart: always

    ports:
      - "27017:27017"

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    command:
      python -u patient_fhir_data/main.py
    links:
      - mongo

